// healthcareFilterWords.js

const greetings = [
    'hello',
    'hi',
    'hey',
    'good morning',
    'good afternoon',
    'good evening',
    'how are you',
    'what\'s up',
    'greetings',
    'salutations',
    'yo',
    'howdy',
    'hi there',
    'hey there',
    'what\'s happening',
    'how\'s it going',
    'nice to see you',
    'pleased to meet you',
    'long time no see',
    'how have you been',
    
    // Acknowledgment
  'okay',
  'ok',
  'sure',
  'got it',
  'understood',
  'acknowledged',
  'roger that',
  // Gratitude
  'thanks',
  'thank you',
  'appreciate it',
  'thanks a lot',
  'thank you so much',
  'much obliged',
  // Agreement
  'yes',
  'yeah',
  'yep',
  'yup',
  'indeed',
  'absolutely',
  'certainly',
  'definitely',
  'of course',
  // Disagreement
  'no',
  'nope',
  'nah',
  'not really',
  'I don\'t think so',
  // Farewell
  'bye',
  'goodbye',
  'see you later',
  'farewell',
  'take care',
  'until next time',
  // Other conversation cues
  'please',
  'excuse me',
  'pardon me',
  'sorry',
  'pardon',
  'beg your pardon',
  'go ahead',
  'what else',
  'anything else',
  'go on',
  'continue',
  'tell me more',
  'explain',
  'clarify',
  ];
  
  
  const healthcareTopics = [
    'health',
    'medical',
    'symptoms',
    'doctor',
    'hospital',
    'clinic',
    'pharmacy',
    'wellness',
    'treatment',
    'diagnosis',
    'prescription',
    'emergency',
    'vaccination',
    'therapy',
    'nutrition',
    'exercise',
    'mental health',
    'disease',
    'injury',
    'surgery',
    'consultation',
    'checkup',
    'rehabilitation',
    'physical therapy',
    'medication',
    'healthcare provider',
    'health condition',
    'medical history',
    'health insurance',
    'public health',
    'primary care',
    'specialist',
    'telemedicine',
    'chronic condition',
    'acute condition',
    'pandemic',
    'immunization',
    'preventive care',
    'homeopathy',
    'alternative medicine',
    'medicine',
  ];
  
  const followUpQuestions = [
    'What are the symptoms of',
    'How do I treat',
    'Can you recommend a doctor for',
   
  ];
  
  export { greetings, healthcareTopics, followUpQuestions };
  