# Generated by Django 4.2.9 on 2024-01-21 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialistcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('medical_license_number', models.CharField(max_length=50)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('medical_certifications', models.TextField()),
                ('telemedicine_schedule', models.DateTimeField(blank=True, null=True)),
                ('secure_messaging_with_patients', models.BooleanField(default=True)),
                ('patient_interaction_history', models.TextField()),
                ('on_call_information', models.TextField()),
                ('emergency_contact_details', models.CharField(max_length=255)),
                ('access_to_patient_records', models.BooleanField(default=True)),
                ('data_privacy_training', models.BooleanField(default=True)),
                ('languages_spoken', models.CharField(max_length=255)),
                ('multilingual_support_preferences', models.BooleanField(default=True)),
                ('patient_ratings', models.FloatField(default=0.0)),
                ('feedback_history', models.TextField()),
                ('access_to_education_materials', models.BooleanField(default=True)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('communication_alerts', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profile_pics/')),
                ('accessibility_tools_preferences', models.BooleanField(default=True)),
                ('notification_preferences', models.BooleanField(default=True)),
                ('account_security_settings', models.BooleanField(default=True)),
                ('data_privacy_info', models.TextField()),
                ('logout_options', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.specialistcategory')),
                ('upcoming_appointments', models.ManyToManyField(related_name='doctor_appointments', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_appointments', to='specialists.specialist')),
            ],
        ),
    ]
