# Generated by Django 4.2.9 on 2024-01-23 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_appointment_created_at_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
