# Generated by Django 4.2.9 on 2024-02-06 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialists', '0007_remove_specialist_upcoming_appointments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
