# Generated by Django 4.2.9 on 2024-03-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0009_remove_specialist_access_to_patient_records_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='Achievements',
            new_name='achievements',
        ),
        migrations.RenameField(
            model_name='specialist',
            old_name='Bankground',
            new_name='background',
        ),
        migrations.AddField(
            model_name='specialist',
            name='facebook',
            field=models.TextField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='specialist',
            name='instagram',
            field=models.TextField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='specialist',
            name='whatsApp',
            field=models.TextField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='specialist',
            name='x',
            field=models.TextField(blank=True, null='True'),
            preserve_default='True',
        ),
    ]
