# Generated by Django 4.2.9 on 2024-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0011_specialist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('approved', 'Approved'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='processing', max_length=20),
        ),
    ]
