# Generated by Django 4.2.9 on 2024-02-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.TextField()),
                ('commitment', models.TextField()),
                ('vision', models.TextField()),
                ('philosophy', models.TextField()),
            ],
        ),
    ]
