export const CategoryData = [
    { name: 'Primary Care' },
    { name: 'Cardiology' },
    { name: 'Dermatology' },
    { name: 'Endocrinology' },
    { name: 'Gastroenterology' },
    { name: 'Hematology' },
    { name: 'Infectious Diseases' },
    { name: 'Nephrology' },
    { name: 'Neurology' },
    { name: 'Ophthalmology' },
    { name: 'Orthopedics' },
    { name: 'Pediatrics' },
    { name: 'Psychiatry' },
    { name: 'Pulmonology' },
    { name: 'Rheumatology' },
    { name: 'Urology' },
    { name: 'Allergy and Immunology' },
    { name: 'Anesthesiology' },
    { name: 'Cardiothoracic Surgery' },
    { name: 'Dental Medicine' },
    { name: 'Emergency Medicine' },
    { name: 'Family Medicine' },
    { name: 'Genetic Counseling' },
    { name: 'Geriatrics' },
    { name: 'Hepatology' },
    { name: 'Integrative Medicine' },
    { name: 'Medical Genetics' },
    { name: 'Oncology' },
    { name: 'Pain Management' },
    { name: 'Radiology' },
  ];
  